version: '3'

services:
  rabbitmq:
    image: rabbitmq:${RABBITMQ_IMAGE_VERSION}
      hostname: rabbitmq
      security_opt:
        - no-new-privileges:true
      <<: *restart-always
      environment:
        RABBITMQ_DEFAULT_USER: ${MESSENGER_TRANSPORT_USER}
        RABBITMQ_DEFAULT_PASS: ${MESSENGER_TRANSPORT_SECRET}
      expose:
        - 5672
        - 15672
      volumes:
        - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
        - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        - rabbitmq_data:/var/lib/rabbitmq
        networks:
          - proxy

volumes:
  rabbitmq_data:
    driver: local

networks:
  proxy:
    external: true
